version: '3.4'
services:
  django:
    env_file: ../.env.dev
    image: mysite-django
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    build:
      context: ..
      dockerfile: ./.ci/Dockerfile
      target: dev
    command: sleep infinity
    volumes:
      - ..:/app
      - /app/vite/node_modules/

  postgres:
    env_file: ../.env.dev
    image: postgres:latest
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
