name: Run all tests
on:
  pull_request:
  push: { branches: docker }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    environment: test
    env:
      MODE: ${{ vars.MODE }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      REDIS_USER: ${{ secrets.REDIS_USER }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PROTOCOL: ${{ secrets.REDIS_PROTOCOL }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
      AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
      AWS_S3_REGION_NAME: ${{ secrets.AWS_S3_REGION_NAME }}
      AWS_S3_PUBLIC_STORAGE_BUCKET_NAME: ${{ secrets.AWS_S3_PUBLIC_STORAGE_BUCKET_NAME }}
      AWS_S3_PRIVATE_STORAGE_BUCKET_NAME: ${{ secrets.AWS_S3_PRIVATE_STORAGE_BUCKET_NAME }}
      AWS_SES_ACCESS_KEY_ID: ${{ secrets.AWS_SES_ACCESS_KEY_ID }}
      AWS_SES_SECRET_ACCESS_KEY: ${{ secrets.AWS_SES_SECRET_ACCESS_KEY }}
      AWS_SES_REGION_NAME: ${{ secrets.AWS_SES_REGION_NAME }}
      AWS_SES_REGION_ENDPOINT: ${{ secrets.AWS_SES_REGION_ENDPOINT }}
      EOD_API_TOKEN: ${{ secrets.EOD_API_TOKEN }}
      SAXO_APP_KEY: ${{ secrets.SAXO_APP_KEY }}
      SAXO_APP_SECRET: ${{ secrets.SAXO_APP_SECRET }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build container for approval tests
      run: docker compose build

    - name: Run approval tests
      run: docker compose run mysite