name: Run all tests
on:
  pull_request:
  push: { branches: main }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build container for approval tests
      run: docker compose -f .ci/test/docker-compose.yml build

    - name: Run approval tests
      run: docker compose -f .ci/test/docker-compose.yml run django

    - name: Run lint and type checker
      run: docker compose -f .ci/test/docker-compose.yml run django ruff . && mypy .
