version: '3.4'
services:
  django:
    env_file: ../../.env.prod
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    build:
      context: ../..
      dockerfile: ./.ci/Dockerfile
      target: prod
    ports:
      - 8000:8000

  postgres:
    image: postgres:15-alpine
    env_file: ../../.env.prod
    expose:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-apline
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5
    expose:
      - "6379:6379"