version: '3.4'
services:
  django:
    depends_on:
     - redis
     - postgres
    build:
      context: ../..
      dockerfile: ./.ci/Dockerfile
      target: prod
    env_file: ../../.env.prod
    ports:
      - "8000:8000"

  postgres:
    image: postgres:15-bookworm
    env_file: ../../.env.prod
    expose:
      - "5432:5432"

  redis:
    image: redis:7-bookworm
    expose:
      - "6379:6379"